theme: minima
title: zacdocs
description: manual for working with zac

header_pages:
  - about.md
  
author:
  name: zachariah cox
  email: zachariahcox@gmail.com

github_username: zachariahcox
linkedin_username: zachariahcox